dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: Bx4Ipo3AgBCnKKsY0tfU6zoXTGqYv0CZDtIHR0yuZ+3RQ2XvdtMlGf9HGFA5cE3/ggOX6SW/OTL4ilBD6Jp27Wc7X1xK5tNp2LKooj3b+K0fd93A+9iSNIpXK25s6OaBCdqZZmuUKmPjebq5fYqIGTGbqyiAMnqjwMs7Hrz6FNxwbMlvJp763Pi/NQMc5REmImn5seiLmrZGbWKK7gcqfnlA/8QNBmzPxLSMyiioVh0CZAyLvgjeI1bC8jZyXkDxmMLlC9/qV5TKVexG0hcl1N6MNfk8ah1u+/CGc5iQ4fzaIdZmsntVZN/9nbSa4dPOzAu7CUFa6Wx2WuEZcZ5K1lstMkgmcyKMYqdpcpO7vGDcgu2kLQ75T8tOQ3xqzYHBNX+w4Ntrr9XFCRPi3VaP1a7wDJcbP8RmZPEsjDAJ4DzqtUlvO4IBPVcz5Th5GGqeelLO8Ynnn6spS3qJ772Tg60lg/inshiyX7ZRD9vtzvvPansjRSBI+1wQJXFFa52ALApoUsnMUjpcvs1O5k9h3TpNRPnxz63KU+jLI+VtWqE54xXl8rNVrTqC4Z+mAdEYRQX5LMZkLZteE6UtXULYCR97QqzqI+wlZ1jDRjxpJzwYCz1LD8oWPHqpuyRuIB2Aekz1h7i0Ketnx6W+/ilhYzn723mOfrDc2IoF+76EnKI=
  file: Gerbers/PIN-105_gerbers.zip
  on:
    repo: w4xzr/PIN-105
  skip_cleanup: 'true'
